name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        working-directory: ./azurepowershell
        run: npm install

      - name: Run Tests
        working-directory: ./azurepowershell
        run: npm test

  deploy:
    needs: build-and-test
    runs-on: windows-latest  # Use Windows runner for PowerShell script execution

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run PowerShell Script to Create VM
        shell: pwsh
        run: |
          # Make sure to use the correct path to your PowerShell script
          .\scripts\create-vm.ps1

      - name: Deploy Code to VM
        run: |
          echo "Deploying the application to the VM..."
          # Use SSH to deploy the code to the VM
          ssh azureadmin@52.233.20.97 "cd /home/azureadmin/azurepowershell && git pull && npm install && npm start"
