name: Run VM Creation Script

on:
  push:
    branches:
      - main  # Adjust if you need a different branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  run-create-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Run PowerShell script on Azure VM
        run: |
          sshpass -p "Welcome@12345" ssh -o StrictHostKeyChecking=no azureadmin@52.233.20.97 "cd /home/azureadmin/azurepowershell && pwsh ./vm-create.ps1"
